name: Deploying Backend

on:
  push:
    branches:
      - main
            
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin            
      - name: Build Docker Image
        run: docker build -t jashan1096/backend-vellura .
      - name: Publish Image to Docker Hub
        run: docker push jashan1096/backend-vellura:latest
    
  deploy: 
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull jashan1096/backend-vellura:latest
      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 --name backend-vellura \
            -e MONGO_URL="${{ secrets.MONGO_URL }}" \
            -e PORT="${{ secrets.PORT }}" \
            -e SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            -e GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
            -e GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
            -e CRYPTO_SECRET_KEY="${{ secrets.CRYPTO_SECRET_KEY }}" \
            -e FRONTEND_URL="${{ secrets.FRONTEND_URL }}" \
            -e SESSION_SECRET="${{ secrets.SESSION_SECRET }}" \
            -e NODE_ENV="${{ secrets.NODE_ENV }}" \
            -e CLOUDINARY_CLOUD_NAME="${{ secrets.CLOUDINARY_CLOUD_NAME }}" \
            -e CLOUDINARY_API_KEY="${{ secrets.CLOUDINARY_API_KEY }}" \
            -e CLOUDINARY_API_SECRET="${{ secrets.CLOUDINARY_API_SECRET }}" \
            -e MONGO_PASSWORD="${{ secrets.MONGO_PASSWORD }}" \
            jashan1096/backend-vellura:latest
